version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "80:8000"
    volumes:
      - .:/code