# Generated by Django 5.1.1 on 2024-09-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplinas',
            new_name='Disciplina',
        ),
    ]
