# Generated by Django 5.1.1 on 2024-09-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_alter_perfil_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
    ]
