# Generated by Django 5.1.1 on 2024-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0006_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='static/img/defaultUserPerfil', upload_to='perfil_pics'),
        ),
    ]
