# Generated by Django 5.1.1 on 2024-09-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0007_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfil_pics/defaultUserPerfil.png', upload_to='perfil_pics'),
        ),
    ]
