# Generated by Django 5.1.1 on 2024-09-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.CharField(max_length=250)),
                ('descrição', models.TextField()),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estante.estante')),
            ],
        ),
    ]
