# Generated by Django 5.1.1 on 2024-09-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
